In [1]:
import gym # pip install gym
import numpy as np
import time
from IPython.display import clear_output

In [23]:
env = gym.make('FrozenLake-v0')

In [24]:
env.render()


SFFF
FHFH
FFFH
HFFG


In [25]:
numActions = env.action_space.n
numStates = env.observation_space.n

In [26]:
print(numActions,numStates)

4 16


In [27]:
Q = np.zeros((numStates,numActions))

In [28]:
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
nE = 10000
mpE = 80
alpha = 0.01
gamma = 0.99
epsilon = 1
edr = 0.0001

In [36]:
for e in range(nE):
    state = env.reset()
    done = False
    for step in range(mpE):
        if np.random.rand() > epsilon:
            action = np.argmax(Q[state,:])
        else:
            action = env.action_space.sample()
        ns,reward,done,info = env.step(action)
        Q[state,action] = (1-alpha)*Q[state,action]+alpha*(
        reward+gamma*np.max(Q[ns,:]))
        state = ns
        if done == True:
            break
    epsilon = epsilon*np.exp(-edr*e)
        

In [37]:
Q

array([[1.30379118e-01, 2.78839342e-02, 2.27452878e-02, 2.00687489e-02],
       [4.67075013e-03, 3.10963783e-03, 4.66701929e-04, 1.08983997e-02],
       [4.23252833e-03, 1.40798504e-03, 1.49006221e-02, 4.88964425e-04],
       [2.06435095e-05, 4.83668241e-04, 3.34624126e-06, 5.98995949e-06],
       [1.31851672e-01, 2.27855192e-02, 1.92902256e-02, 1.53996854e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.04758617e-02, 1.23507914e-01, 1.68762538e-04, 2.16160218e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.07485775e-02, 1.34009747e-01, 1.97772255e-02, 3.34101881e-02],
       [1.58737677e-02, 2.75387182e-02, 2.94823313e-01, 2.51476083e-02],
       [3.86342973e-01, 2.71018936e-02, 9.38386664e-03, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.74051524e-03, 2.79718075e-02, 4.81410045e

In [38]:
for e in range(4):
    state = env.reset()
    done = False
    print("Episode::",e)
    time.sleep(0.1)
    for step in range(mpE):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(Q[state,:])
        ns,reward,done,info = env.step(action)
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("Goal")
                time.sleep(3)
            else:
                print("Hole")
                time.sleep(3)
                clear_output(wait=True)
            break
        state = ns
env.close()
            
            

  (Right)
SFFF
FHFH
FFFH
HFFG
Goal
