In [10]:
import numpy as np

In [11]:
Q = np.empty((9,9))
Q[:] = np.nan
Q[0,[0,1,3]]=0
Q[1,[0,1,2,4]] = 0
Q[2,[1,2,5]] = 0
Q[3,[0,3,4]] = 0
Q[4,[1,3,4,5,7]] = 0
Q[5,[2,4,5,8]] = 0
Q[6,[3,6,7]] = 0
Q[7,[4,6,7,8]] = 0
Q[8,[5,7,8]] = 0

In [12]:
Q

array([[ 0.,  0., nan,  0., nan, nan, nan, nan, nan],
       [ 0.,  0.,  0., nan,  0., nan, nan, nan, nan],
       [nan,  0.,  0., nan, nan,  0., nan, nan, nan],
       [ 0., nan, nan,  0.,  0., nan, nan, nan, nan],
       [nan,  0., nan,  0.,  0.,  0., nan,  0., nan],
       [nan, nan,  0., nan,  0.,  0., nan, nan,  0.],
       [nan, nan, nan,  0., nan, nan,  0.,  0., nan],
       [nan, nan, nan, nan,  0., nan,  0.,  0.,  0.],
       [nan, nan, nan, nan, nan,  0., nan,  0.,  0.]])

In [13]:
R = Q
idx = np.isnan(R[:,4])
R[~idx,4] = -1
idx = np.isnan(R[:,8])
R[~idx,8] = 1

In [14]:
R

array([[ 0.,  0., nan,  0., nan, nan, nan, nan, nan],
       [ 0.,  0.,  0., nan, -1., nan, nan, nan, nan],
       [nan,  0.,  0., nan, nan,  0., nan, nan, nan],
       [ 0., nan, nan,  0., -1., nan, nan, nan, nan],
       [nan,  0., nan,  0., -1.,  0., nan,  0., nan],
       [nan, nan,  0., nan, -1.,  0., nan, nan,  1.],
       [nan, nan, nan,  0., nan, nan,  0.,  0., nan],
       [nan, nan, nan, nan, -1., nan,  0.,  0.,  1.],
       [nan, nan, nan, nan, nan,  0., nan,  0.,  1.]])

In [15]:
MAXEPISODES = 100
NUMSTATES = 9
gamma = 0.5
TerminalState = 8

In [16]:
for k in range(MAXEPISODES):
    alpha = 1/(k+1)
    i = np.random.permutation(np.arange(NUMSTATES))[0]
    while True:
        selectMax = False
        if np.random.rand() < 0.5:
            selectMax = True
        idx = np.isnan(Q[i,:])
        allowedStates = np.arange(NUMSTATES)[~idx]
        j = Q[i,allowedStates].argmax()
        if selectMax:
            j = allowedStates[j]
        else:
            j = np.random.permutation(allowedStates)[0]
        Q[i,j] = Q[i,j]+alpha*(R[i,j]+gamma*np.nanmax(Q[j,:])-Q[i,j])
        if i == TerminalState:
            break
        i=j

In [17]:
Q

array([[ 3.00777648e-02,  6.09964639e-01,             nan,
         2.77407990e-03,             nan,             nan,
                    nan,             nan,             nan],
       [ 3.04954181e-02,  2.10611639e-01,  2.18694602e+00,
                    nan, -8.98586499e-01,             nan,
                    nan,             nan,             nan],
       [            nan,  3.98862124e-01,  4.26708268e-01,
                    nan,             nan,  4.02058195e+00,
                    nan,             nan,             nan],
       [ 7.94519889e-02,             nan,             nan,
         2.91338152e-03, -9.44116284e-01,             nan,
                    nan,             nan,             nan],
       [            nan,  9.62562031e-02,             nan,
         1.61441848e-03, -9.10504419e-01,  1.77202158e+00,
                    nan,  5.88326084e-02,             nan],
       [            nan,             nan,  8.69153157e-01,
                    nan, -7.85260592e-01,  7.616122

In [20]:
i = 6
NUMTRANS = 10
for k in range(NUMTRANS):
    print(i)
    idx = np.isnan(Q[i,:])
    allowedStates = np.arange(9)[~idx]
    j = Q[i,allowedStates].argmax()
    j = allowedStates[j]
    i = j

6
7
8
8
8
8
8
8
8
8
